name: AWS Terraform & Ansible Automation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: infrastructure

      - name: Validate Terraform
        run: terraform validate
        working-directory: infrastructure

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: infrastructure

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          echo "EC2_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=WebServer" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)" >> $GITHUB_ENV

      - name: Wait for EC2 to be Ready
        run: sleep 60

      - name: Copy SSH Key to GitHub Runner
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > labsuser.pem
          chmod 400 labsuser.pem

      - name: Run Ansible Playbook
        run: |
          echo "[webserver]" > inventory.ini
          echo "${{ env.EC2_PUBLIC_IP }} ansible_user=ec2-user ansible_ssh_private_key_file=./labsuser.pem" >> inventory.ini
          ansible-playbook -i inventory.ini ansible/install_docker.yml
