- name: Deploy Docker Container
  hosts: all
  become: yes
  tasks:

    - name: Pull Nginx Docker Image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

      - name: Download index.html from GitHub
        get_url:
          url: "https://github.com/ZohaibYar/AWSNetwork/blob/main/ansible/index.html"
          dest: "/home/ec2-user/index.html"


    - name: Run Nginx Container with Custom Web Page
      community.docker.docker_container:
        name: webserver
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - "/home/ec2-user/index.html:/usr/share/nginx/html/index.html"
