
- name: Deploy Docker Container
  hosts: all
  become: yes
  tasks:
    - name: Pull Nginx Docker Image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Create index.html File on EC2
      copy:
        dest: "/home/ec2-user/index.html"
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Netwoking Assignment</title>
          </head>
          <body>
              <h1 style="text-align: center; color: #4CAF50;">Weerahennedige Hashmi Sathnara</h1>
              <p>NGNIX is running on Docker </p>
              <h2 style="text-align: center;">B9IS121 - Network Systems and<br>Administration CA 2025</h2>
              <h1>Assignment Complete </h1>
          </body>
          </html>
        mode: '0644'

    - name: Run Nginx Container with Custom Web Page
      community.docker.docker_container:
        name: webserver
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - "/home/ec2-user/index.html:/usr/share/nginx/html/index.html"
