- name: Configure Web Server
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Ensure system is updated
      package:
        name: "*"
        state: latest

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker and enable it on boot
      service:
        name: docker
        state: started
        enabled: yes
