- name: Configure Web Server
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Ensure system is updated
      package:
        name: "*"
        state: latest

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker and enable it on boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure pip and setuptools are installed via system package manager
      package:
        name:
          - python3-pip
          - python3-setuptools
        state: latest

    - name: Upgrade pip and setuptools using pip
      command: /usr/bin/pip3 install --upgrade --ignore-installed pip setuptools

    - name: Install Docker Python module
      command: /usr/bin/pip3 install docker --break-system-packages

    - name: Restart Docker service
      service:
        name: docker
        state: restarted
