- name: Configure Web Server
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Ensure system is updated
      package:
        name: "*"
        state: latest

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker and enable it on boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install pip
      package:
        name: python3-pip
        state: present

    - name: Upgrade pip and setuptools
      pip:
        name:
          - pip
          - setuptools
        state: latest
        executable: pip3

    - name: Install Docker Python module
      pip:
        name: docker
        executable: pip3

    - name: Restart Docker service
      service:
        name: docker
        state: restarted
