- name: Configure Web Server
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Ensure system is updated
      package:
        name: "*"
        state: latest

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker and enable it on boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure required system packages are installed (without python3-docker)
      package:
        name:
          - python3-pip
          - python3-setuptools
          - python3-requests
        state: latest

    - name: Check if python3-docker is available
      command: yum list python3-docker
      register: python3_docker_check
      failed_when: false
      changed_when: false

    - name: Install python3-docker if available
      package:
        name: python3-docker
        state: latest
      when: "'python3-docker' in python3_docker_check.stdout"

    - name: Install Docker Python module using pip (only if package manager installation failed)
      command: /usr/bin/pip3 install --no-deps docker
      when: "'python3-docker' not in python3_docker_check.stdout"

    - name: Restart Docker service
      service:
        name: docker
        state: restarted
