yaml
Copy code
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd myapp
            git pull origin main
            docker build -t my-nginx .
            docker stop my-nginx || true
            docker rm my-nginx || true
            docker run -d -p 80:80 my-nginx
